### ISSUE TITLE
disable brightness bar

### ISSUE THREAD

**Issue by replicat0r** [jaames/iro.js#10]
Hi, 

let me say this first, this is one of the best color picker wheel implementations out there! simple to easy, low friction api and very well designed!

I just had a question, is there a way for me to disable the brightness bar? or a way to pass in a init option? 

Thanks!

**Comment by replicat0r** [comment]
Also I cant seem to register a callback on my color picker with watch 

if i have the following 
        var colorPicker = new iro.ColorPicker("#example");
        colorPicker.watch(function(newHsv, oldHsv, changed) {
	// if the hue channel changed, log the new hue value to the console:
    if(changed.h) {
		console.log(newHsv.h)
    }

    // if the saturation channel changed, log the old saturation value to the console:
    if(changed.s) {
		console.log(oldHsv.s)
    }
})

seems like changed becomes undefined. 

am i doing something wrong?

**Comment by jaames** [comment]
Hello! Thank you very much, I'm glad you like the library!

There was another request to make the brightness slider optional, if that's something you'd like to see then feel free to join the discussion on [this thread](https://github.com/jaames/iro.js/issues/9), and let me know what you think of the suggested changes. :>

----

Regarding the `watch` method, iirc this behaviour was changed in the transition between v1 + v2. Currently, the watch callback is only provided the color picker's [`color`](https://github.com/jaames/iro.js/blob/master/docs/color_api.md) object.

That said, if you would like the `changed` value to be added back to the watch method callback, that can certainly be done.

**Comment by jaames** [comment]
iro.js version 4.0.0 is now live, which provides the ability to disable the brightness bar with the new [custom layout](https://iro.js.org/guide.html#custom-layouts) option:

```js
var colorPicker = new iro.ColorPicker('#color-picker', {
  layout: [
    {
      component: iro.ui.Wheel,
      options: {}
    }
  ]
});
```

--

Sorry for taking so long to find a good way to implement this!
