### ISSUE TITLE
Slider styles, width, orientation, etc

### ISSUE THREAD

**Issue by rwwagner90** [jaames/iro.js#103]
Hi @jaames! Question for you: Is there a way to make the sliders vertical rather than horizontal and/or adjust their size or switch out the svgs?

Also, I know you can switch the handle svgs, but is it possible to also switch only the selected handle? I was hoping to make the currently active color's handle larger to differentiate it.

Basically, we are looking to build the below screenshot and looking for help with what is currently possible or what could possibly be implemented?

<img width="283" alt="Screen Shot 2020-03-10 at 2 08 45 PM" src="https://user-images.githubusercontent.com/2640861/76345043-09333e80-62d9-11ea-825f-056e56694c9b.png">

**Comment by rwwagner90** [comment]
All of this seems to be possible via https://iro.js.org/guide.html#color-picker-options so never mind!

**Comment by jaames** [comment]
@rwwagner90 Hey, sorry for not replying sooner! 

Yeah, most of this can be done by tweaking the `layoutDirection` and the `sliderSize` color picker options. I recently also made it easier to style the handles, so with a bit of CSS you could scale the active handle:

```css
.IroWheel .IroHandle--isActive circle,
.IroBox .IroHandle--isActive circle {
    transform: scale(1.2);
}
```

The only thing that might be a bit hacky is making the sliders taller than the color wheel. It could technically be done by giving each components its own `width` value, but then you'd need to use flexbox or something to make sure the components line up properly.

**Comment by rwwagner90** [comment]
<img width="359" alt="Screen Shot 2020-03-15 at 6 07 54 PM" src="https://user-images.githubusercontent.com/2640861/76711589-e6919300-66e7-11ea-91d4-d67a9cae246e.png">

@jaames here is what we have been working on. Is there a way to flip the sliders to the left side instead of being on the right?

**Comment by rwwagner90** [comment]
Ahhhh,, never mind, things are inserted in order, so switching the order gives us what we need 🎉
