### ISSUE TITLE
Change color temprature range

### ISSUE THREAD

**Issue by icodesdeveloper** [jaames/iro.js#105]
Hello,
When i create a color temprature kelvin slider the default range is 2194.0536499023438
to 10991.905212402344. 

Is there a possibilty to make te range larger? If so, how? If not, i hope you will implement this.

Regards,
Kuno

**Comment by jaames** [comment]
I forgot to document it (sorry!) but this is actually implemented!

When creating the kelvin slider, you can set min and max temperature range:

```js
var colorPicker = new iro.ColorPicker('#picker', {
  layout: [
    { 
      component: iro.ui.Slider,
      options: {
        sliderType: 'kelvin',
        minTemperature: 2000,
        maxTemperature: 30000,
      }
    },
  ]
});
```

The smallest possible temperature value is `1000`, the largest is `40000`.

Again, sorry that's not documented!

**Comment by icodesdeveloper** [comment]
Ok,
Thank you.
I personally think that your documentation isnt one of the easiest to
understand. (Not bad meant but just to be direct)
Buy your app self is great.

Regards
Kuno
