### ISSUE TITLE
Resizing with Percentage

### ISSUE THREAD

**Issue by Aaron-Mann** [jaames/iro.js#106]
```
var colorPicker = new iro.ColorPicker("#color-picker-container1", {
        // Set the size of the color picker
        width: 90%
      });
```

I have a color-picker built into a web app, and I would like it to resize to it's container based off of screen size. However, I can't seem to find a way to set it's width value to a percentage. Am I missing something obvious, or is this not a feature yet?

**Comment by angelofan** [comment]
@Aaron-Mann I also hope that iro provides a percentage width setting method, but as a temporary solution, I did this:

html:
```
<div id="color-card">
  <div id="color-picker-container"></div>
</div>
```

JavaScript:
```
let cardWith = document.getElementById('color-card').offsetWidth;
this.colorPickerForRGBMode = new iro.ColorPicker("#color-picker-container", {
  // Set the size of the color picker
  width: cardWith*0.7
});
```

**Comment by Aaron-Mann** [comment]
Perfect! Thanks for your quick response. Would be a great future issue.
