### ISSUE TITLE
wheelDirection support dropped in 5.x release?

### ISSUE THREAD

**Issue by joshualyon** [jaames/iro.js#111]
Hi @jaames - excellent work on the updates in the 5.x series.

One thing I noticed is that the `wheelDirection` option no longer seems to be supported in the 5.x series and the default wheel direction seems to be reversed compared to previous releases.

For example, most of the screenshots in the project show the wheel in what I believe is the `anticlockwise` direction with red on the right, green in the top-left, and blue in the bottom-left. 

For example, here's the image from the top of the main `README.md` file:

![image](https://user-images.githubusercontent.com/966456/80040678-3bcb7c00-84c0-11ea-91e7-39c7c6d578e2.png)

Interestingly, the automatic screenshot on the [Interactive Samples](https://codepen.io/collection/XQgGRB) page in Codepen linked from https://iro.js.org/introduction.html even still shows the original default with green in the top-left:

![image](https://user-images.githubusercontent.com/966456/80040827-8816bc00-84c0-11ea-9283-136a6c5bc950.png)

But when that [CodePen in the bottom-right](https://codepen.io/rakujira/pen/WZOeNq) is run, it pulls in the newest Iro.js which appears to follow the clockwise pattern which has the green in the bottom left:

![image](https://user-images.githubusercontent.com/966456/80040889-b1cfe300-84c0-11ea-8d2c-ed5ba4d4cea7.png)

Manually updating the dependency back to a 4.x branch resolves the issue and the `wheelDirection` option is respected and seems to default to `anticlockwise` as the document indicates that it should:

![image](https://user-images.githubusercontent.com/966456/80041080-1b4ff180-84c1-11ea-8250-3d9210e16757.png)

**Comment by jaames** [comment]
Oops, sorry about that, looks like something must have broken at some point even though I thought I tested that pretty thoroughly. I'll look into fixing that whenever I get a free moment

**Comment by joshualyon** [comment]
Hi @jaames any tips on where I might start looking to figure out why `wheelDirection` isn't working?

**Comment by rjsachse** [comment]
Any Update? Are you and your family O.K?

**Comment by jaames** [comment]
This should now be fixed with 5.4.0

Sorry for the extremely slow response on this, I've just started to work on iro.js again after a long semi-hiatus. It's been a while :)
