### ISSUE TITLE
Change the DOM parent of a layout component

### ISSUE THREAD

**Issue by DeveloperBlue** [jaames/iro.js#113]
I have ColorPicker object whose layout is made up of two components, a wheel and a slider.
Is there any way to re-parent just the slider DOM object somewhere else?

I would like to avoid creating a new ColorPicker object for slider, because the colors between the wheel and the slider would not be synced. I can't seem to find anything related to this in the documentation.

```javascript
let color_picker = new iro.ColorPicker(".color-wheel", {
	width : 256,
	height : 256,
	handleRadius : 8,
	wheelLightness : false,
	layout : [
		{
			component : iro.ui.Wheel
		},
		{
			component : iro.ui.Slider // I'd like to parent this to something else, that's not the constructor's ".color-wheel", but still have it synced to the wheel when the color changes.
		},
	]
});
```

**Comment by jaames** [comment]
Hm, unfortunately I don't think this is going to be possible without some major internal reworks or hacks, and that's not really something I'm willing to do at the moment 

All I can suggest is maybe using two color picker objects and using their events to hook them together such that a color change event on one will change the color on the other?

**Comment by DeveloperBlue** [comment]
Thanks,

I ended up doing exactly that as you suggested for a work around. I was initially worried that having the two ColorPicker objects listening to each other's changed events and updating would cause some sort of feedback loop, but thankfully that did't happen.

As a suggestion for a possible future implementation, a ColorPicker object's `color` property could accept references to a Color object, that way multiple ColorPicker objects could refer that one Color object.

The workaround was extremely straightforward and solved the issue, so I'll go ahead and close this.
