### ISSUE TITLE
[feature] Smoother hue color ramps

### ISSUE THREAD

**Issue by jaames** [jaames/iro.js#114]
Note to future James: it might be interesting to incorporate something like Jim Bumgardner's "sinebows" to have smoother hue ramps:

https://observablehq.com/@mbostock/sinebow

http://basecase.org/env/on-rainbows

https://www.shadertoy.com/view/4tlBWB

https://observablehq.com/@mattdesl/perceptually-smooth-multi-color-linear-gradients

**Comment by rjsachse** [comment]
FastLed for the arduino family has this too... Might be good to look at to

**Comment by drzony** [comment]
Just a word of warning, messing with rainbows might pose a problem.
Although they will look better, they will incompatible with other HSV.
As @rjsachse mentioned FastLED has it, but it means that green on FastLED is (H=96, S=100, V=100) and on iro it's (H=85, S=100, V=100). [Here](https://github.com/FastLED/FastLED/wiki/FastLED-HSV-Colors) are the details

**Comment by jaames** [comment]
@drzony In this case it wouldn't affect how the color is actually chosen -- iro.js never picks from what's drawn on the screen anyway, it just figures out what the color should be based on the position of the handles. Because of that, I think I can justify messing with it a tiny bit to make it look nicer :)

I'm basically looking into adding an (optional) way to smooth out the sharper parts of the hue ramp around where the color approaches cyan, magenta and yellow:

<img width="346" alt="Screenshot 2020-08-11 at 22 34 52" src="https://user-images.githubusercontent.com/9112876/89951508-739f3080-dc23-11ea-8a03-abf5975d85a0.png">

**Comment by drzony** [comment]
Yes, but if you smooth it out, take the position of the handles, then put the value of the color into some other software, then the color under the handle will look different than the color in this other software. It may even look different than the color on the lower slider. Maybe it won't be noticeable, maybe it will be very confusing to the user. I just wanted to point your attention to it. I'm doing a project on FastLED and matching what's on screen with LED color calibration is already a nightmare, without adding any more surprises to it :)
