### ISSUE TITLE
Event Step Delay

### ISSUE THREAD

**Issue by xRealNeon** [jaames/iro.js#115]
Hello I wanted to ask if i can adjust how often the color change event is triggered?

**Comment by jaames** [comment]
This isn't built into the library, but you can have your event handler call a [**throttled or debounced** function](https://css-tricks.com/debouncing-throttling-explained-examples/), depending on your use-case

**Comment by xRealNeon** [comment]
I don't get it can you give me an example how to do that that every half second the event is send
