### ISSUE TITLE
Setting RGB values after initialising picker limits the RGB values

### ISSUE THREAD

**Issue by jeremy-smith-maco** [jaames/iro.js#122]
I am not sure if I am doing something wrong or not but after I init a picker and then change the RGB values programatically, using the picker to select a colour will not print out any RGB values above the numbers that I specified when setting it. Here is some test code using the codepen example:

```
// Create a new color picker instance
// https://iro.js.org/guide.html#getting-started
var colorPicker = new iro.ColorPicker(".colorPicker", {
  // color picker options
  // Option guide: https://iro.js.org/guide.html#color-picker-options
  width: 280,
  color: "rgb(255, 0, 0)",
  borderWidth: 1,
  borderColor: "#fff",
  wheelLightness: false,
});
colorPicker.color.rgb = { r: 10, g: 10, b: 10 }; // This line will make it so the RGB values do not go above 10

var values = document.getElementById("values");

// https://iro.js.org/guide.html#color-picker-events
colorPicker.on(["color:init", "color:change"], function(color){
  // Show the current color in different formats
  // Using the selected color: https://iro.js.org/guide.html#selected-color-api
  values.innerHTML = [
    "hex: " + color.hexString,
    "rgb: " + color.rgbString,
    "hsl: " + color.hslString,
  ].join("<br>");
});
```

Same thing happens if you set it to a big number (i.e. `colorPicker.color.set({ r: 5434343, g: 5343434, b: 5343434 });`), it will limit the maximum RGB to those numbers. It seems to scaling or something? I may just have an option not set correctly, I am not sure.

Any help is appreciated. Thanks.

**Comment by jaames** [comment]
I can't seem to recreate this, and I'm fairly sure there isn't anything in the code that would cause this either

Have you been using the value slider to adjust the color, or are you just using the hue/saturation wheel to test? I ask because using the wheel only adjusts the hue/saturation, not the value, so that might be why your RGB values might seem to be "clamped"; in this case it isn't a bug, it's just how the RGB colorspace works :)

**Comment by jeremy-smith-maco** [comment]
Oh, I definitely just misunderstood how a colour wheel works. I didn't realise it was only for setting the hue and saturation. I was only showing the wheel in our project and using that to select an RGB value but we also need the slider. Thanks for your help.
