### ISSUE TITLE
Kelvin slider produces invalid color

### ISSUE THREAD

**Issue by martin2250** [jaames/iro.js#124]
Hi James,

I just found a potential issue with 'kelvin' type sliders. When placing the slider exactly in the center, the resulting color has a hexstring of '#100f8ff', aka a red component of 256
![image](https://user-images.githubusercontent.com/8293473/90114378-ed820780-dd52-11ea-9b49-c4388eb8582a.png)

No special settings required, my code is
```
    this.colorPicker = new iro.ColorPicker('#picker', {
      layout: [
        {
          component: iro.ui.Wheel
        },
        {
          component: iro.ui.Slider
        },
        {
          component: iro.ui.Slider,
          options: {
            sliderType: 'kelvin'
          }
        }
      ]
    })
```
and it will reproduce in the official demo after adding a kelvin slider
![image](https://user-images.githubusercontent.com/8293473/90114665-52d5f880-dd53-11ea-93da-ba54798328c9.png)

Cheers,
Martin

**Comment by jaames** [comment]
@martin2250 

Hey Martin! Thanks for reporting that, looks like I neglected to clamp the RGB values after converting the kelvin temperature

My bad, should be fixed now :)

**Comment by martin2250** [comment]
Thanks, awesome!
