### ISSUE TITLE
colorpicker does not work on touching screen PC

### ISSUE THREAD

**Issue by SmartCodeDavid** [jaames/iro.js#126]
The touching events are not triggered when users interact with the color picker. These issues only occur on the touching screen laptop or PC. 

I did a fork and go through and trace all of the codes. The reason is because 'onTouchStart' event at ComponentBase.tsx is not existed in DOM, thus, it has been added as a customized event in this situation. 
![image](https://user-images.githubusercontent.com/30002112/91140516-3e461880-e6e2-11ea-9454-5e9d75330bc9.png)

Address this problem through adding 'ontouchstart '
![image](https://user-images.githubusercontent.com/30002112/91141733-95e48400-e6e2-11ea-85db-cd2c89865936.png)

**Comment by jaames** [comment]
Hi, saw your PR earlier and left a comment there, please check it when you can! Thanks!

**Comment by jaames** [comment]
fixed in #127
