### ISSUE TITLE
[Feature Request ] Ring shaped UI Component (around Wheel)

### ISSUE THREAD

**Issue by gitchomik** [jaames/iro.js#128]
Ring shaped UI Component with same functions as sliders that allow the user to adjust a specific color channel. 
- multiple rings types covering hue, saturation, value, red, green, blue, alpha
- multiple rings around the iro.ui.Wheel

Or maybe just extend component: iro.ui.Slider options `sliderShape: 'ring'`
I think that it will looks very nice, especially around the `iro.ui.Wheel`

Example:
https://www.canva.com/colors/color-wheel/

**Comment by jaames** [comment]
This is something I'd really like as well! Implementation-wise it'd be pretty difficult though, especially with current layout stuff and the lack of real conical gradient support in SVG

Maybe one day :)
