### ISSUE TITLE
colorPicker.d.ts name change in v5.2.1 breaks linux builds

### ISSUE THREAD

**Issue by colorado-nate** [jaames/iro.js#129]
The filename for colorPicker.d.ts changed case in version 5.2.1 from ColorPicker.d.ts to colorPicker.d.ts.  This works fine on Windows, but breaks on Linux because ComponentBase.d.ts has "import { IroColorPicker } from './ColorPicker';" in it.  That won't find colorPicker.d.ts on Linux.

**Comment by jaames** [comment]
Huh, that's really weird, not entirely sure how that happened. Should be fixed now regardless. Thanks!

**Comment by colorado-nate** [comment]
Awesome!  Does this mean that a v5.2.2 will be released soon?  Just curious on your process..  Thanks!

**Comment by jaames** [comment]
@colorado-nate yeah, it should be available now, I published 5.2.2 on npm etc a couple of minutes after pushing the fix on Github :)

**Comment by colorado-nate** [comment]
That fixed it, thank you for the quick response!

**Comment by jaames** [comment]
no worries! ✨
