### ISSUE TITLE
[Feature Request] Setting color rage

### ISSUE THREAD

**Issue by gitchomik** [jaames/iro.js#133]
Please, add setting the range of colors (resolution), ie the possibility of "RGB scaling".

Currently, the resolution of each color is 8 bits (256 different values ​​from 0-255), which makes a total of 256 * 256 * 256 = 16,777,216 colors.

Each area (one-point area of ​​the color wheel) represents one of 16,777,216 color. For example, when the range will be 0-3, the possible colors will be 4 * 4 * 4 = 64 (represents the visible number of different color areas in on the picker component). For example, value (1,2,3) means rgbString = "rgb (64,127,255)", (0,1,2) = rgb (0,64,127) etc.

The current 8-bit resolution is excellent when using HTML, but in many cases such a wide and precise color palette is not needed. In many cases, eg the range 0-100 is sufficient (eg for PWM duty cycle control of the LED brightness).

**Comment by jaames** [comment]
>Please, add setting the range of colors (resolution)
Allowing the color bitdepth to be variable would require a significant amount of additional UI code to display the limited color selection, and I don't think I'm really willing to do that for a relatively niche feature to be honest. Sorry about that

> eg the range 0-100 is sufficient (eg for PWM duty cycle control of the LED brightness)
I don't work with LEDs so I'm not really sure what this means, but I heard a lot of LEDs use different RGB scales and need gamma adjustments etc so maybe you're talking about that? I don't think this is something that should be covered by iro.js either; it's a color picker, not an LED driver, so you'll need to do whatever math is necessary to adjust the color to something that works with your hardware yourself.

**Comment by gitchomik** [comment]
@jaames I understand, no problem.

And for your information, your project is great for controlling LEDs (I use it myself in my software to control LED strips). 
See an example of use
https://randomnerdtutorials.com/esp32-esp8266-rgb-led-strip-web-server/ where another simple HTML color picker was used (range 0-255). In my case, I used your picker.
However, due to some LED driver limitation, I will scale your full 24-bit palette to 0-100 rage, due to driver limitation (http://wiringpi.com/reference/software-pwm-library/)

When it comes to PWM control, it is about the percentage of filling in which it is easier to operate in the range of 0-100
(more information here https://en.wikipedia.org/wiki/Pulse-width_modulation)

Best Regards.

**Comment by jaames** [comment]
If you just need to get the color's RGB values in the 0-100 range, the math is pretty simple:

```js
const colorPicker = new iro.ColorPicker();
// color.rgb gives the rgb values in the 0-255 range
const rgb = colorPicker.color.rgb;
// convert to 0-100 range:
const r = Math.round(rgb.r / 2.55);
const g = Math.round(rgb.g / 2.55);
const b = Math.round(rgb.b / 2.55);
```
