### ISSUE TITLE
Color export with mouseup event

### ISSUE THREAD

**Issue by fm0609** [jaames/iro.js#137]
Thanks a lot for presenting the Color Picker API. In your example code you use: 

`colorPicker.on("color:change", colorChangeCallback); `

Is it also possible to use a different event for triggering the function? Like `onmouseup` ? That would be a simple way to reduce the outgoing commands. Would be happy to hear from you :-)
Regards
Michael

**Comment by jaames** [comment]
There's a couple of different events available, you can find a list of them here:
https://iro.js.org/colorPicker_api.html#events

If you want something that only fires on mouse up, I think you're looking for `input:end`

**Comment by fm0609** [comment]
Perfect! Sometimes it is so easy!! Thank you for the quick reply and the great tool!! We are also working with HUE. Might it be possible to get output color data in `xy` values?

**Comment by jaames** [comment]
No worries! Not sure what you mean by xy values?
