### ISSUE TITLE
Get color.hsvString

### ISSUE THREAD

**Issue by niwanta** [jaames/iro.js#148]
1)Is it possible to get `color.hsvString`?
2)If not I can get `color.hsv.h, color.hsv.s, color.hsv.v` separately but how to get percentage(%) of `color.hsv.s, color.hsv.v` values?
3)I add hue slider, and is it possible to lock the hue slider on a given value when init?
```
component: iro.ui.Slider,
options: {
sliderType: 'hue'
```
4)Is it possible to increase the range 100 and above?

**Comment by jaames** [comment]
> Is it possible to get `color.hsvString`. 
Yeah, I'll implement something like that in the future. My plan is to add support for most of the CSS Level 4 spec in the next major version of iro.js

> If not I can get `color.hsv.h`, `color.hsv.s`, `color.hsv.v` separately but how to get percentage(%) of `color.hsv.s`, `color.hsv.v` values?

I don't really understand what you mean here? `hsv.s` and `hsv.v` are already in the range of 0 to 100, like a percentag.

> I add hue slider, and is it possible to lock the hue slider on a given value when init?

Kinda, you can force one of the color channels to always have the same value:
```js
colorPicker.on('change', function() {
  // whenever the color changes, force the hue value back to 100
  color.hue = 100;
});
```

> Is it possible to increase the range 100 and above?

I'm not sure I understand this either

**Comment by niwanta** [comment]
No worries, successfully implemented the color picker. 
Some color pickers I've seen S and V values can be adjusted from 0-255.
But 0-100 worked for me.

**Comment by jaames** [comment]
> But some color pickers I've seen S and V values can be adjusted from 0-255.

to convert `x` from 0-100 to 0-255 you can just do `x * 2.55`. I don't see why the color picker needs to do this

**Comment by marekburiak** [comment]
Instead of 255 steps you only have 100 so you're loosing precision. Obviously niwanta didn't mind.
