### ISSUE TITLE
Allow kelvin in Color constructor

### ISSUE THREAD

**Issue by RyanMcDonald** [jaames/iro.js#149]
I've created a color temperature picker React component that wraps iro, and my React component would be used something like this:

```jsx
const [kelvin, setKelvin] = useState(6500);
<ColorTemperaturePicker color={kelvin} onChange={setKelvin} />
```

In my `ColorTemperaturePicker` implementation, it's just slightly inconvenient to have to convert my kelvin value back to RGB so that `iro.Color` can use it:
```js
// color comes from component props
new iro.ColorPicker(el, {
  color: iro.Color.kelvinToRgb(color), // <--
});

// Update iro's color every time the color prop changes
useEffect(() => {
  const updatedColor = iro.Color.kelvinToRgb(color); // <--
  colorPicker.current.color.set(updatedColor);
}, [color]);
```

Is there any reason the `iro.Color` constructor can't accept kelvin format as well?

**Comment by jaames** [comment]
Ah, this is a silly oversight on my behalf, sorry about that. 

It should be relatively trivial to add support for specifying the initial color as an object like `{kelvin: 9000}`, I'll take a look at it whenever I have time :)

**Comment by jaames** [comment]
Sorry for taking so long to get to this, the option to pass a kelvin object as a color value will be added in the next release (v 5.5.0)

Example:

```js
colorPicker.color.set({ kelvin: 6600 });
```
