### ISSUE TITLE
Colorpicker resize

### ISSUE THREAD

**Issue by niwanta** [jaames/iro.js#153]
Tried `colorPicker.resize( width )` but no effect at all.
Tried this way also https://github.com/jaames/iro.js/issues/55
But not working.

**Comment by jaames** [comment]
@niwanta Can you share your code? The resize method is working fine when I test it.

**Comment by jaames** [comment]
Closing this for now since it's been a week without any response, and this doesn't seem like a bug in iro.js. Feel free to comment or re-open if you have any additional information though.
