### ISSUE TITLE
Uncaught TypeError: Container is null

### ISSUE THREAD

**Issue by danielschlingmeier** [jaames/iro.js#155]
Hello!

A first thanks a lot for this nice color picker! I used it on my ESP8226 Smart Lamp project for quite a while now and I like it! :) However I updated today from an old version (please don't ask me which one, some years old :-)) and now Firefox Console throws a failure:
![grafik](https://user-images.githubusercontent.com/76655064/103173465-69d93b00-485b-11eb-8d04-5de95e04993e.png)

I am not an expert, but I had a look at the code and it seems it has something to do with finding the HTML container aka parent element of type div, which does obviously fail and return a null. I double checked my HTML and JS and copied in the example code in the end, but it didn't change anything:

![grafik](https://user-images.githubusercontent.com/76655064/103173773-8a09f980-485d-11eb-9990-a0d36187876c.png)

![grafik](https://user-images.githubusercontent.com/76655064/103173786-9e4df680-485d-11eb-8af6-3f006ccde33e.png)

However the color picker works so far (surprisingly), I can use the events, so it works so far. What doesn't work is accessing it via its HTML ID or class via CSS, which points a bit into the direction as well, I think.

Best regards
Daniel

**Comment by jaames** [comment]
Hi! Thanks for the kind words :)

I'm not really sure what's causing this, it looks like you might be trying to create a new color picker before the HTML container for it has been loaded and parsed? iro.js should be able to handle that though, so this is weird :/

I can't recreate it myself, so if you're able to reproduce the problem in a Codepen or a Github repo that would be really helpful. Cheers!

**Comment by danielschlingmeier** [comment]
Hello!

Okay, I found the problem and I have to admit it is basically sitting in front of my screen :D

This happens, when one copy&pastes the Color Picker object creation snipplet from one place to another in the java script, renames the HTML ID of the <div> container forgets about the old code. The pasted code snipplet works, but the old one complains that it can't find the container under the given name...and justifiably so.

Anyway the error is gone now. Sorry for bothering you with my learning JavaScript problems here :-)

**Comment by jaames** [comment]
No worries! Good to see that you got to the bottom of it anyway :)
