### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by riegel** [jaames/iro.js#160]
I am using the color wheel to calculate a directional vector for a pan/tilt/zoom camera controller. Is there an easy way to make all the colors white?

thanks

**Comment by jaames** [comment]
Sorry for the slow response. Assuming you're using multiple colors on the same wheel, you can loop through them and set them to the same value:

```js
// multi-color picker setup
const colorPicker = new iro.ColorPicker(".colorPicker", {
  colors: [
    "rgb(255, 0, 0)",
    "rgb(0, 255, 0)",
    "rgb(0, 0, 255)",
  ],
});

// to reset all the colors to white:
colorPicker.colors.forEach(function (color) {
  color.set('#fff');
});
```
