### ISSUE TITLE
Bug: IE11 mouseup events

### ISSUE THREAD

**Issue by michaelfarrelly** [jaames/iro.js#163]
IE11 mouse up events are not removed fully, related to older issue #58:

https://github.com/jaames/iro.js/blob/master/src/ComponentWrapper.tsx#L95

Recommend change from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener):
from: `document.removeEventListener(event, this);`
to: `document.removeEventListener(event, this, { passive: false });`

This matches the `addEventListener` options.

**Comment by jaames** [comment]
good catch! should be fixed in the next release (5.3.2)
