### ISSUE TITLE
Google Chrome Violation: Added non-passive event

### ISSUE THREAD

**Issue by aletheia7** [jaames/iro.js#164]
### Google Chrome Console Error
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

macOS: Big Sur
Google Chrome: 89.0.4389.82
iro.js: v5.3.2

iro.js line 14
iro.js chrome formatted: line 241
### Code

```
... u ? (t || n.addEventListener(l, T, e), ...
l = onmousedown
e = false
e should probably be { passive: true }

also
l = ontouchstart
e = false
```
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by jaames** [comment]
I intentionally mark them as non-passive: https://github.com/jaames/iro.js/blob/master/src/ComponentWrapper.tsx#L83

IIRC, marking them as passive would cause the page to scroll when users try to drag the color picker handle on certain mobile browsers.

**Comment by aletheia7** [comment]
When I sent a breakpoint, e is a boolean. e is not an object with passive set to false.

Would the Violation disappear if e was {passive: false} ?

**Comment by jaames** [comment]
Ah, looks like that code is coming from Preact, so not sure if there's anything I can do about that.

Relevant Preact issue:
https://github.com/preactjs/preact/issues/428
