### ISSUE TITLE
Implement preset colors (Swatches)

### ISSUE THREAD

**Issue by mardzo** [jaames/iro.js#17]
Hello,

Nice job with the picker. It would be nice for the user to have some basic preset colors to choose from, underneath the picker.
Cheers

**Comment by jaames** [comment]
Hello! Thanks for the feature request.

At the moment I can't see this being implemented into the main library, to be honest. I'm trying to keep the library's footprint relatively small, so I try to only add features if they will benefit most of the people using it. In this case, I feel like the requested feature is simple enough for a developer to implement themselves (e.g they can make some small squares with HTML + CSS below the color picker, then when the user clicks, [set the color picker](https://rakujira.jp/projects/iro/docs/guide.html#Getting-and-Setting-the-Color) to a given value, maybe from a [data-attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes)).

With that said, I have been considering adding a plugin API to the library when I get the time. I'll make a note of your request and perhaps look at incorporating it into a UI plugin in the future. :)
