### ISSUE TITLE
One RGB circle, multiple independent hue sliders

### ISSUE THREAD

**Issue by mcer12** [jaames/iro.js#191]
This is probably very unusual but I want the user to pick a color and then I would like to have 3 independent hue sliders to pick 3 brightness values. Is this possible without combining multiple colorpickers? If this outputs 3 different colors or 1 color +3 hue values doesn't matter. :)

**Comment by jaames** [comment]
This isn't currently possible without using separate color pickers, but that may change in the future

**Comment by mcer12** [comment]
It all worked out in the end :) I just want to say thank you for this great tool, I've implemented this in my Arduino project, see screenshot of the web UI.
https://github.com/mcer12/Flora-ESP8266/
Since the code is directly embedded in the sketch, I hope there's no licensing issue (iro.js license is mentioned at the bottom of readme).
