### ISSUE TITLE
Alpha channel not kept when creating a new iro Color object based on an existing one

### ISSUE THREAD

**Issue by Asmor** [jaames/iro.js#193]
In the screenshot below, `foo` is an iro Color object created by passing in the string `rgba(0,0,0,0)`. `foo`'s alpha channel is correctly set to 0. `bar` is an iro Color object created by passing in `foo`. 'bar`'s alpha channel is 1.

![image](https://user-images.githubusercontent.com/2127204/121564255-40ffc900-c9e9-11eb-9124-edb1d58bb783.png)

Here's another screenshot demonstrating that the color channels are being copied correctly, it's only the alpha channel having the issue.

![image](https://user-images.githubusercontent.com/2127204/121564581-9d62e880-c9e9-11eb-9abc-bef9bda35d09.png)

I can also confirm the issue is not unique to objects created with rgba strings; I had the same results using e.g. `#ffffff00`.

**Comment by jaames** [comment]
sorry for the wait on both of these! should be fixed now :)
