### ISSUE TITLE
hslaString doesn't actually return an hsla string

### ISSUE THREAD

**Issue by Asmor** [jaames/iro.js#194]
the Color object's `hslaString` property returns a string starting with `hsl`, not `hsla`. This causes problems if the same string is then loaded into iro, as iro will not look for the alpha channel if the string is `hsl` and not `hsla`.

Demonstrating bad return value

![image](https://user-images.githubusercontent.com/2127204/121619244-4afbe900-ca36-11eb-8817-39aa03e1c456.png)

Demonstrating that the alpha channel works with `hsla` but not with `hsl`

![image](https://user-images.githubusercontent.com/2127204/121619400-8bf3fd80-ca36-11eb-992c-874353ba7eb9.png)

**Comment by jaames** [comment]
thanks! should be fixed with version 5.5.2
