### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null on laravel8

### ISSUE THREAD

**Issue by hung2707** [jaames/iro.js#208]
issue: Uncaught TypeError: Cannot read property 'appendChild' of null on laravel8
screenshot: https://i.imgur.com/weBdblC.png

**Comment by jaames** [comment]
Hi,

You're probably not passing a valid HTML element to the `new iro.ColorPicker(...)` constructor

This is probably a bug in your code somewhere, I can't really help further without seeing it.
