### ISSUE TITLE
Request for a second horizontal slider for alpha transparency

### ISSUE THREAD

**Issue by nickbe** [jaames/iro.js#22]
Is it possible to add an option for an additional transparency slider? This would make the color picker so perfect.
Thanks.

**Comment by jaames** [comment]
Thanks for the request! The transparency slider has kinda been on the back burner for a while ahah.

I'll try to push it along a bit, but at the moment my focus is on other things. Hopefully that doesn't cause you too much convenience

**Comment by nickbe** [comment]
I'm using the Jquery mini colorpicker right now. So it works.
But once iro has transparency I'll switch immediately and any effort on your side will be much appreciated :-)

**Comment by jaames** [comment]
I just released a [transparency plugin](https://github.com/jaames/iro-transparency-plugin) for iro.js, which can be used to add an alpha slider to the color picker: 

![screenshot](https://user-images.githubusercontent.com/9112876/53989190-58222300-411d-11e9-893e-c0fbe5f1b042.png)

@nickbe sorry for taking so long to get this out (over a year...) ':)
