### ISSUE TITLE
Usage with Angular

### ISSUE THREAD

**Issue by qMalte** [jaames/iro.js#221]
Hello together,

I would like to use this library with Angular.

The problem is, that my typescript Compiler gives the following error:
`Error: src/app/components/lights/ColorPicker/ColorPicker.component.ts:15:23 - error TS2350: Only a void function can be called with the 'new' keyword.`

Is this error known?

I am glad about your answers.

Best Regards

Malte

**Comment by jaames** [comment]
I don't know anything about angular, but I don't recognise ColorPicker.component.ts as part of iro.js, I think this error is coming from your own code. It may also help to update your TypeScript version.
