### ISSUE TITLE
Svg, display:block

### ISSUE THREAD

**Issue by gadlol** [jaames/iro.js#23]
In line 1380:

`  svgElement.call(this, this, parent, "svg", { width: width, height: height, style: "display:block" });`

It would be better if that "display:block" was a param so we could add for example "display:inline-block".

**Comment by jaames** [comment]
Thanks for the suggestion, I agree that it might be worthwhile to provide an option to change the SVG's display attribute. Will try adding it now :)

**Comment by jaames** [comment]
As of c080c1252672ee9aadd5e04b21a846620c34f6ed, `iro.ColorPicker` instances now have a `display` param that can be used to set the color picker's CSS display property. It will default to "block" to preserve past behaviour. 

Docs have been updated to reflect this change: https://rakujira.jp/projects/iro/docs/guide.html#Color-Picker-Options
