### ISSUE TITLE
aliased edges on both wheel and slider when surrounding graphics are dark

### ISSUE THREAD

**Issue by chuank** [jaames/iro.js#231]
When using a dark surrounding palette for the color wheel + slider, the edge of both elements show a ring of aliased pixels that seem to be a result of the black value graphic element not completely filling up the underlying colour svg.

To better explain this with images:
![image](https://user-images.githubusercontent.com/1781911/166409007-1639942b-90f2-43b6-b8e2-b807898cd3e9.png)

Will it make sense to draw this value shading element just a hair larger so the aliased edges can be concealed?
Exposing an offset property to adjust this manually will be great, too.

**Comment by mxdmly** [comment]
![image](https://user-images.githubusercontent.com/17523786/170629326-23c01196-d26c-4381-b73e-99dd03aa74c4.png)
I have this trouble too
Increasing the value of borderWidth has a more obvious effect
