### ISSUE TITLE
Inside popover

### ISSUE THREAD

**Issue by ajtudela** [jaames/iro.js#236]
Hi, 

Thanks for your amazing library!

I'm tryint to use it in a website but I've some issues implementing it. I'm trying to put it inside a popover without success. When I click in the popover, the colorpicker shows as it used to but the selector don't move. 

Any thought?

P.S.: I can copy some cde if you need to.

Thanks

**Comment by jaames** [comment]
It's not the responsibility of an open source maintainer to do your job for you.
