### ISSUE TITLE
Request: Pass color param to callback function for the other events also

### ISSUE THREAD

**Issue by gadlol** [jaames/iro.js#24]
It would be nice to also pass color params to callback function for the events: 

input:start and input:end

especially for input:end.

Right now we have to do:

```
demoColorPicker.on("input:end", function onInputEnd() {
  console.log(demoColorPicker.color.hexString);
});

```

It would be better to also do:

```
demoColorPicker.on("input:end", function onInputEnd(color) {
  console.log(color.hexString);
});
```

**Comment by jaames** [comment]
Sorry for such a slow response on this, I meant to get to it sooner. The color object should be available as a param for both the `input:start` and `input:end` events as of da84bd9 :)
