### ISSUE TITLE
Update the border color on input?

### ISSUE THREAD

**Issue by Newbrict** [jaames/iro.js#241]
Hi, I wanted to have the border color update to the selected color. I tried this:

```js
color_picker.on('color:change', (color) => {
  color_picker.borderColor = color.hexString;
});
```

But the border does not get redrawn. Is this possible with iro currently?
Thanks.

**Comment by jaames** [comment]
i think i forgot to document it but there is a [setOptions](https://github.com/jaames/iro.js/blob/master/src/ColorPicker.tsx#L223) method that can update props after the color picker has been created. `color_picker.setOptions({borderColor: color.hexString});` should do it.

**Comment by Newbrict** [comment]
> i think i forgot to document it but there is a [setOptions](https://github.com/jaames/iro.js/blob/master/src/ColorPicker.tsx#L223) method that can update props after the color picker has been created. `color_picker.setOptions({borderColor: color.hexString});` should do it.

That works, thank you.
