### ISSUE TITLE
Add lighter color spectrum to brightness slider 

### ISSUE THREAD

**Issue by BennyAlex** [jaames/iro.js#244]
Hello,

It would be nice to change not only the color to a darker one but also to a brighter, so the slider would be something like this

![image](https://user-images.githubusercontent.com/17402724/202069226-2fe24723-846b-40a2-a934-e0c9cd3d5fa0.png)

I tried it by my own, but doing this from outside the picker is hard.

**Comment by jaames** [comment]
sounds like you want to add either a value or saturation slider: https://iro.js.org/advanced.html#sliders

**Comment by BennyAlex** [comment]
> sounds like you want to add either a value or saturation slider: https://iro.js.org/advanced.html#sliders

It looks like there is no slifer thats going from white to COLOR to Black, only Eiter color to Black or color to white
