### ISSUE TITLE
Passive Event Listener

### ISSUE THREAD

**Issue by Kamephis2000** [jaames/iro.js#247]
Hello,
I recently encountered a warning in the Chrome Debugger while using this script. 
The warning is shown in the following screenshot:

![image](https://user-images.githubusercontent.com/52784377/218067365-456c48b6-e554-4641-b803-600f503857a6.png)

Here is the mentiond link from the screenshot: 
https://www.chromestatus.com/feature/5745543795965952

I am using the development version of the script in a self-hosted manner. The warning occurs on line 14 of the code, which is quite lengthy and difficult for me to interpret.

Is there a way for me to resolve this warning or will there be an update for the package in the future?

Thank you and best regards,
Frank

**Comment by jaames** [comment]
It's just a best-practice warning. Last time I checked, using this type of event listener was correct for this particular use-case, so it can be ignored.
