### ISSUE TITLE
Some colors get rounded by iro.Color

### ISSUE THREAD

**Issue by nickpearson** [jaames/iro.js#26]
`iro.Color` seems to round the rgb values in some cases:

```javascript
new iro.Color("#fff").hexString //=> "#fff"    (ok)
new iro.Color("#eee").hexString //=> "#ededed" (rounded)
new iro.Color("#ddd").hexString //=> "#dedede" (rounded)
new iro.Color("#ccc").hexString //=> "#ccc"    (ok)
```

You can also see this effect by modifying the [CodePen Demo](https://codepen.io/rakujira/pen/WZOeNq?editors=0010) (linked on the [intro](https://rakujira.jp/projects/iro/docs/introduction.html) page) to use `#eee` as the `color` option rather than `{r: 255, g: 0, b: 0}`.

**Comment by jaames** [comment]
Thanks for letting me know!

I *think* it might be due to how all `iro.Color` instances use HSV colors internally, and some rounding when converting RGB -> HSV -> RGB is causing the effect you're seeing. I'll have to investigate further, though

**Comment by mbaierl** [comment]
Just noticed the same issue... #FF0FF0 -> #FF0FEF and some others...

**Comment by jaames** [comment]
Finally found the cause; it was a combination of excessive rounding and a strange quirk where converting decimal numbers to hex with `.toString(16)` would produce unexpected output

I have a working fix in the [bug/color-rounding](https://github.com/jaames/iro.js/tree/bug/color-rounding) branch if anyone wants to try it

One minor side effect of this fix is that `hexString` will only provide 6-digit hex output now (e.g `new iro.Color("#fff").hexString` will be `"#ffffff"`, not `"#fff"` as before). I can reimplement the shorthand 3-digit output if someone complains, but tbh I feel like keeping it consistent makes more sense anyway

**Comment by jaames** [comment]
Okay I think I got it, the fix should be in master now. Thanks @nickpearson and @mbaierl :)

**Comment by nickpearson** [comment]
Works great. Thank you!

I agree that always using the full hex string for consistency is good. If you do happen to decide to convert to the shorthand hex value, here's a simple implementation:

```javascript
function shortHex(hex) {
  return hex.replace(/^#([0-9a-f])\1([0-9a-f])\2([0-9a-f])\3$/, "#$1$2$3")
}
```

```javascript
shortHex("#aabbcc") //=> "#abc"
shortHex("#aabbcd") //=> "#aabbcd"
shortHex("testing") //=> "testing" (returns non-compactible values untouched)
shortHex("#abc")    //=> "#abc"
```

This implementation of course doesn't do validation and only compacts all-lowercase hex strings, but it's a start.
