### ISSUE TITLE
Request: issue event after colorPicker has been initialized

### ISSUE THREAD

**Issue by mbaierl** [jaames/iro.js#28]
Right now a `new iro.ColorPicker(...)` immediately returns an object but finishes initialisation of the object after the document.readyState changed to "complete". 

It would be amazing if there would be an event issued after the _init function finished doing its job and the  colorPicker object is completely initialized.

For example the following at the end of the _init function:
```
_init: function _init(el, opts) {
    ...
    this.emit("initialized", this);
},
```

Thanks!

**Comment by jaames** [comment]
Thank you for the request! This would definitely be a helpful addition so I'll work on adding it ASAP :)

I think I'll probably call the event `mount` or something like that, to signify that the color picker has been mounted into the DOM

**Comment by mbaierl** [comment]
Thanks James!

**Comment by jaames** [comment]
The `mount` event should be available now, thanks again @mbaierl!

Here's a usage example:
```js
// create a new color picker instance
var example = new iro.ColorPicker(...);

example.on("mount", function() {
  // do something
});
```

In addition, the color object is now passed to the `input:start` and `input:end` events, which was requested a while ago in #24
