### ISSUE TITLE
Request: A few options for responsive design

### ISSUE THREAD

**Issue by thuyettiensinh** [jaames/iro.js#32]
`let colorPicker = new iro.ColorPicker("#color-picker", {`
`    width: 320,`
`    height: 320`
`}`

How can i responsive design with this ?
because i only see fixed width and heigh on colorPicker object !

**Comment by adrianjost** [comment]
You could read the width of the outer div and calculate the height based on that. If you want to be completly responsive you need to add an eventHandler for resizing of the outer div and update the width and height according to that.

**Comment by jaames** [comment]
Hi, sorry that you've been having issues there! Unfortunately I can only suggest trying @adrianjost's workaround for now :)

The way iro.js does layout is kinda complicated just due to the nature of SVG, it's one of the things I really want to improve with 4.0, I'm just a little busy with other projects at the moment

**Comment by thuyettiensinh** [comment]
Thanks, 
I'm tried the way @adrianjost suggested before. But I really think if you can add the request to new feature then it will awesome more :grin:

**Comment by jaames** [comment]
The [iro.js v4 beta](https://github.com/jaames/iro.js/tree/v4) is out now, which adds a `resize()` method which can change the width of the color picker at any time. 

Here's a basic example:

```html
<html>
  <head>
    <script src="https://unpkg.com/@jaames/iro@beta/dist/iro.js"></script>
  </head>
  <body>
    <div id="color-picker-mount"></div>
    <script>
       var colorPicker = new iro.ColorPicker("#color-picker-mount", {
         width: 300,
       });

       // whenever you need to resize, call the resize() method with your new width:
       var newWidth = 200;
       colorPicker.resize(newWidth);
    </script>
  </body>
</html>
```

**Comment by thuyettiensinh** [comment]
=)) here is my result.
create by iro

![circle-color-picker](https://user-images.githubusercontent.com/21211244/51735928-4e87b300-20bb-11e9-8cfa-2a7823a353e2.png)

**Comment by jaames** [comment]
Neat! I'm going to close this thread now. Let me know if theres anything else you need :)

**Comment by rwwagner90** [comment]
@thuyettiensinh how did you do multiple colors on the wheel?

**Comment by thuyettiensinh** [comment]
@rwwagner90 
I just get the coordinates of color selected and push to the colors coordinates list and then render on the wheel. Make sure you allow wheel have css `position: relative` and color picked is `position: absolute`
By the way, I'm using vuejs to make this, you can refer to the following below (image attached)

![irojs](https://user-images.githubusercontent.com/21211244/71819484-a2b65800-30be-11ea-9ecd-bcb0e7ea9310.png)

**Comment by thuyettiensinh** [comment]
I'm not sure it can work for now, because it's the two years ago :thinking: :thinking: 
But you can think about my stupid idea :grin: :grin:

I hope it can help you @rwwagner90
