### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by mhadaily** [jaames/iro.js#36]
Hi
I was playing with the library a bit and it seems there an error in Chrome 68 at least. 

`[Intervention] Unable to preventDefault inside passive event listener due to the target being treated as passive. See https://www.chromestatus.com/features/5093566007214080` => iro.js:1025

iro.js:1025 is 
```
switch (e.type) {
      ...
      case EVENT_MOUSEUP:
      case EVENT_TOUCHEND:
        this._mouseTarget = false;
        this.emit("input:end", this.color);
        unlisten(document, [EVENT_MOUSEMOVE, EVENT_TOUCHMOVE, EVENT_MOUSEUP, EVENT_TOUCHEND], this);
        break;
    }
    if (this._mouseTarget) {
      e.preventDefault();  // HERE IS LINE 1025 
    }
  }
```

I just wanted to inform you. If I continue using your library, I will fix and will send a PR. 

Thanks for your cool library.

**Comment by jaames** [comment]
Thanks for letting me know! Just pushed a fixed for this and updated the NPM package :)

**Comment by mhadaily** [comment]
Thanks, it's was very quick but doesn't seem it solved the issue completely. 

You might need to add one more thing to the color picker container element which is 
```touch-action: none;``` 

Thanks for your hard work.

**Comment by jaames** [comment]
Ah got it, thanks for the tip!

`touchmove` events are now also passive, and the color picker's SVG root elements should also have `touch-action: none;` applied. :)
