### ISSUE TITLE
Request: Add "How to easily customize the svg layout" to the documentation.

### ISSUE THREAD

**Issue by mrwhy-orig** [jaames/iro.js#44]
I'd like to change the svg layout to 4:3 square and I like to be able to change the color gradients. I had a look in the docs but couldn't find something related to it.

**Comment by DenVys** [comment]
@mrwhy-orig what do you mean "change the color gradient" ?

**Comment by jaames** [comment]
The current customisation options are already documented here: https://iro.js.org/guide.html#color-picker-options

It's not possible to change the layout that much at the moment. That is something being considered for the next major release (v4). You're welcome to join the v4 discussion thread (#30) and suggest ideas, though!
