### ISSUE TITLE
Set the color by an HSL string

### ISSUE THREAD

**Issue by obscuredetour** [jaames/iro.js#50]
Hey @jaames,

First of all let me say that [iro.js](https://github.com/jaames/iro.js) is excellent! As you know I am using it in my pwa [Color Deck](https://color.obscuredetour.com).

I found a bug when setting the color using an HSL string. It causes iro.js to crash, with only a reload fixing it. This can be recreated in the [iro.js demo](https://codepen.io/rakujira/pen/WZOeNq?editors=0011) (as shown below). Open the *Console* and type `colorPicker.color.hslString = 'hsl(182, 35%, 65%)'`.

![iro js_hslstring](https://user-images.githubusercontent.com/25191266/51808804-ee794400-2255-11e9-9041-add7c8cb4748.gif)

I did notice that this extends to parsing an HSL string with the `iro.Color.parseHslStr` method as well. It returns *'parsed is null'*. Perhaps, the two are related?

**Comment by jaames** [comment]
Hi @obscuredetour, thank you for the bug report!

I can confirm this is an issue on my end too. My guess is that the `parseHslStr` method isn't parsing the regex matches from the hsl string correctly (and `hslString` isn't working too since it uses this method internally). I'll take a look at it now.  

Also thanks for the kind words! I'm happy to hear you chose iro.js for your app. Sorry about the awkward bug. :P

**Comment by jaames** [comment]
Ahah, seems like `parseHslStr` wasn't taking the right array values from the hsl string regex match. Just pushed a hotfix now -- hopefully that should solve it. 

I think I'm also going to start implementing code tests to make sure something like that doesn't end up in the library again. Sorry for the trouble!

----

By the way, I'm currently working on the next major release of iro.js. You're welcome to join the [v4 discussion thread](https://github.com/jaames/iro.js/issues/30) if you have any feature suggestions or other feedback after using the library in your project. :)

**Comment by obscuredetour** [comment]
Thanks so much for the fix @jaames! That was fast :+1: 

I started testing v4 #30 in my project on a separate branch, but couldn't get many methods to work. So I'll wait for more of your awesome documentation. :smile: I am liking many of the features listed! I will add any I deem worthy. Thanks again!

**Comment by jaames** [comment]
Hey @obscuredetour! I finally got around to making the final changes on v4 and pushed it into production, the new documentation is live on https://iro.js.org now too :)
