### ISSUE TITLE
iro.js with React

### ISSUE THREAD

**Issue by Ermilin** [jaames/iro.js#54]
Hi, this project looks very promising.

How do I use this with react? I am trying to create a new picker with a unique id in every loop of my map function. 

<img width="380" alt="screenshot 2019-02-26 at 19 36 16" src="https://user-images.githubusercontent.com/21192205/53437430-ce2bd900-39fd-11e9-81ff-c193cdeb11bf.png">

As seen in this picture I want to control the color of each controller with a picker for every card.

**Comment by jaames** [comment]
Hey @Ermilin, thank you for the kind words!

At the moment I would recommend wrapping the color picker with a react component, something like this:

```js
class IroColorPicker extends React.Component {
  componentDidMount() {
    // create a new iro color picker and pass component props to it
    this.colorPicker = new iro.ColorPicker(this.e, this.props);
  }

  componentWillReceiveProps(newProps) {
    // isolate color from the rest of the props
    const {color, ...state} = newProps;
    // update color
    this.colorPicker.color.set(color);
    // push rest of the component props to the colorPicker's state
    this.colorPicker.setState(state);
  }

  render() {
    return (
      <div ref={el => this.el = el} />
    );
  }
}
```

This component will take all the iro.ColorPicker options via props, and it will also update the color picker whenever any of these prop values change. 

I understand this isn't ideal. I fully intend to give the library a "true" React port when I have the time, but until then I hope that this suffices.

**Comment by Ermilin** [comment]
Thank you for the quick reply, I'll look into it tomorrow. Good night!

**Comment by Ermilin** [comment]
I can't get it working, could you provide a working example with several colorpicker componenets?

**Comment by Ermilin** [comment]
Your edited post works like a charm! Thank you so much for this project! Love ya.

**Comment by jaames** [comment]
Ahah, no worries! Sorry for not making the edit clearer -- my initial example wasn't tested ":)

Best of luck with your project!

**Comment by sarahgould** [comment]
When I try using iro.js (4.2.2) with Preact (8.4.2), I find that once the parent component gets updated, iro disappears. Any ideas on how to prevent that from happening without creating a new color picker every update?

**Comment by jaames** [comment]
Nice catch @sarahgould ! If that doesn't work out I'm wondering if it might be better to replace `React.Component` with `React.PureComponent` (which is also in preact-compat iirc), as recommended by the React docs?

**Comment by bertyhell** [comment]
With hooks it looks something like this:

```typescript
import React, { FunctionComponent, MutableRefObject, useEffect, useRef } from 'react';
import iro from '@jaames/iro';

import './ColorInput.scss';

interface IroColorPicker {
  on: (action: string, callback: Function) => void;
  color: {
    set: (value: any) => void;
    setState: (state: any) => void;
  }
}

export interface ColorInputProps {
  value?: string;
  onChange?: (color: string) => void;
}

const ColorInput: FunctionComponent<ColorInputProps> = ({
                                                          value = '#850000',
                                                          onChange = () => {}
                                                        }) => {
  let colorPicker: MutableRefObject<IroColorPicker | null> = useRef<IroColorPicker | null>(null);
  let el: HTMLDivElement | null = null;

  useEffect(() => {
    // create a new iro color picker and pass component props to it
    colorPicker.current = new iro.ColorPicker(el, { color: value });
    // call onColorChange prop whenever the color changes
    if (!colorPicker.current) {
      return;
    }
    colorPicker.current.on('color:change', (color: { hexString}) => {
      onChange(color.hexString);
    });
  }, [el, onChange]);

  useEffect(() => {
    if (!colorPicker.current) {
      return;
    }
    colorPicker.current.color.set(value);
    // this.colorPicker.setState(colorPickerState);
  });

  return <div
    ref={refEl => el = refEl}
  />;
};

export default ColorInput;
```

**Comment by mydudechris** [comment]
@jaames your solution works well for setting up a single picker & slider, but how would you address a layout with multiple components? For example, a wheel + ui.Slider (value) + ui.Slider (alpha).

Thanks! 👍
