### ISSUE TITLE
IE11problem

### ISSUE THREAD

**Issue by pavel-nitka** [jaames/iro.js#58]
Hi, 
i faced with problem when tried to use this awesome color picker in IE11. In IE11 picker doesn`t ends selection at 'mouseup' event. Seems problem in this function:
```
function unlisten(el, eventList, callback) {
	  for (var i = 0; i < eventList.length; i++) {
	    el.removeEventListener(eventList[i], callback);
	  }
}
```

in IE removeEventListener doesn`t removes event handler. To resolve this issue, you must modify the function as follows:
```
	function unlisten(el, eventList, callback) {
	  for (var i = 0; i < eventList.length; i++) {
	    el.removeEventListener(eventList[i], callback, { capture: false });
	  }
	}
```

**Comment by jaames** [comment]
Hey, thanks for a bug report! I’m sorry you’ve been having trouble with iro.js

I’ll look into the problem and try to issue a fix for it later on today. :)

**Comment by jaames** [comment]
So according to the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener), you need to pass the same event parameters to `addEventListener` *and* `removeEventListener` in order for it to correctly remove the event. 

Just pushed a hotfix that should fix this issue. Thank you @pavel-nitka for the bug report!
