### ISSUE TITLE
color:change fires before input:start

### ISSUE THREAD

**Issue by ywwg** [jaames/iro.js#59]
I'm using input:start and :end to disambiguate when the user makes a change vs when the color changes by code. When I see input:start, I set a boolean to indicate the user is interacting.  When I see input:end, I turn it off.  However due to the order of the events, this doesn't work.  If I click on the color picker (at least on firefox), the events are:

1. color:change
2. input:start
3. input:end

Steps 1 and 2 should be swapped.

I am able to work around this issue by manually calling my onColorChange handler inside my input:start handler, but this seems like something that should be fixed.

**Comment by jaames** [comment]
Hey! Thanks for flagging this issue

I agree that your suggested event order makes more sense, I've just pushed a hotfix (ver 4.2.2) which should fix that. 👍

It's worth noting that color:update also (intentionally) fires once with the initial color value too

**Comment by jaames** [comment]
As of [v4.3.0](https://github.com/jaames/iro.js/blob/master/CHANGELOG.md#430) there's now a built-in `input:change` event that should do exactly what you want -- it's identical to `color:change` except it only fires with user input.

**Comment by ile** [comment]
Hmm. Are you sure this works in the latest version (@jaames/iro@5.2.3).

I'm seeing `input:start` firing after `input:change` and it also fires twice in "Box" (https://codepen.io/rakujira/pen/XWbgwYm). This happens, when I click just once in Box (on my development machine):

![image](https://user-images.githubusercontent.com/433707/94355721-22da7e80-008f-11eb-88ae-209d2fe0f5a7.png)

**Comment by jaames** [comment]
@ile this is a different issue, but yes it looks like you're right. I'll take a look after the weekend
