### ISSUE TITLE
Rotate / flip the circle

### ISSUE THREAD

**Issue by mcer12** [jaames/iro.js#66]
Hi @jaames  Is there a way to rotate or flip (mirror) the color picker circle? For example I would need Red on top, Green on the right and Blue on the left?

**Comment by jaames** [comment]
Hey @mcer12!

At the moment there isn't an option to adjust the hue wheel's angle or direction. I chose not to add that since I didn't see any particular benefit and thought it would just add extra complexity. 

That said, I can probably add it when I have the time. What's your use-case here? How urgently is this needed?

**Comment by mcer12** [comment]
The goal is to make web interface to control philips Hue, that means to make the color picker similar to that on the linked picture.
https://2672686a4cf38e8c2458-2712e00ea34e3076747650c92426bbb5.ssl.cf1.rackcdn.com/2018-05-20-05-57-17.jpeg

**Comment by jaames** [comment]
Ah, rad. I'll have a look at implementing this sometime (by adding `wheelAngle` and `wheelDirection` options to iro.ColorPicker?). I'm slightly busy this week so it'll probably be Saturday at the soonest, hope that's okay

**Comment by mcer12** [comment]
Sounds like exactly what I need!

**Comment by jaames** [comment]
Currently working on this over in the features/hue-wheel-angle branch if you'd like to take a look!

I've implemented `wheelAngle` and `wheelDirection` options for the color picker constructor, docs still need to be written but `wheelAngle` is the number of degrees to rotate the wheel by (always in a clockwise direction) and `wheelDirection` is the direction to draw the hue in -- either `"anticlockwise"` or `"clockwise"`

Here's an example:

<img width="319" alt="Screenshot 2019-05-10 at 01 29 06" src="https://user-images.githubusercontent.com/9112876/57494832-16e7f400-72c3-11e9-9350-f2cdc3797fc3.png">

**Comment by jaames** [comment]
@mcer12 Just pushed this feature in iro.js 4.4.0! 

To get the result you're looking for, you'll need to set `wheelDirection` and `wheelAngle` like so:

```js
var colorPicker = new iro.ColorPicker({
  ...
  wheelAngle: 270,
  wheelDirection: 'clockwise',
})
```

Documentation is also available on the project's GitHub readme and on https://iro.js.org

Gonna close this thread now, but feel free to comment or open up another thread if there's anything else you need!

**Comment by mcer12** [comment]
Thank you very much, this is exactly what I needed. Great improvement!

**Comment by jaames** [comment]
Awesome, glad I could help!
