### ISSUE TITLE
[feature-request] kelvin scale colors

### ISSUE THREAD

**Issue by KaanMol** [jaames/iro.js#69]
Hey James,
I was trying to make it by myself in Iro.JS, but I don't really know anything about colors etc.
Maybe you can do it or help me make it.
I need a colorwheel like this basically: 
![20190519_113723](https://user-images.githubusercontent.com/21340806/57980357-ffc7a580-7a2a-11e9-9659-052d1c00165f.jpg)

Do you know how I can achieve this?

**Comment by jaames** [comment]
This control seems to represent the kelvin scale, which measures color warmth and is often used in lighting

It would normally just be controlled with a slider, but I guess they made it look like a circle for aesthetic reasons -- it does look pretty nice!

It shouldn't be too hard to implement something like this in iro.js, maybe as a plugin. The UI is just a circle with a gradient, and I think there's already formulas out there for converting a kelvin value to/from an approximate rgb color but that would probably be the trickiest bit to implement

I'll look into it a bit more next week :)

**Comment by KaanMol** [comment]
Maybe it is an option to just put the Kelvin Scale utils in Iro.JS? Would be handy if a person wouldn't want the wheel but rather a slider.
I've found a couple ways to implement the Kelvin Scale, one is to calculate it (I also found the way to calculate it, quite easy) and the other is just to use an enum full of the RGB values of the tempratures.

**Comment by jaames** [comment]
My goal with iro's core library is to keep it relatively small and free of feature-bloat, so any new features should only be things that most users will find useful. Not everybody is using iro to control lightning so I think it makes more sense to implement this as an optional plugin, like https://github.com/jaames/iro-transparency-plugin

There's probably some other features that would be helpful for lighting control too, so perhaps this new plugin could basically turn iro into the ultimate lighting tool for users who want such a thing :)

And yeah, the best option is probably to use math to convert kelvin temperature <-> rgb, and allow for the temperature range to be customised

**Comment by siggerzz** [comment]
I'm also really interested in this functionality, as I have the exact same use case. However I don't have the knowledge to implement this myself.

@KaanMol Did find a way to implement this at all (using iro / other implementation)?

**Comment by rjsachse** [comment]
+1 for this

**Comment by 13546777510** [comment]
+1 , Smart home needs it.

**Comment by DanielPeinhopf** [comment]
+1 👍

**Comment by jaames** [comment]
<img width="359" alt="Screenshot 2019-10-20 at 21 51 22" src="https://user-images.githubusercontent.com/9112876/67166036-d3baa280-f383-11e9-8467-f4cc0f6614e9.png">

I began implementing support for kelvin temperatures as well as a kelvin slider :)

This will be released as part of [iro.js 5.0](83)

**Comment by jaames** [comment]
<img width="327" alt="Screenshot 2019-10-21 at 01 08 32" src="https://user-images.githubusercontent.com/9112876/67168776-54d36300-f39f-11e9-8b66-6658ca102c0f.png">

I also tentatively implemented a circular slider type like the one used in @KaanMol's screenshot, does anyone care about this in particular? Or is having a simple kelvin slider type fine?

**Comment by 13546777510** [comment]
@jaames Wow, it’s cool! I think it can be used as an option. You can choose it yourself through the layout option. That would be great.

Like this:
```
var colorPicker = new iro.ColorPicker('#color-picker', {
  layout: [
    {
      component: iro.ui.Wheel,
      options: {}
    },
    {
      component: iro.ui.Slider,
      options: {}
    }
  ]
});
```

**Comment by jaames** [comment]
That's the plan! To make a circular kelvin slider like in my last screenshot, `layout` would look like this:

```
layout: [
    ...
    {
      component: iro.ui.Slider,
      options: {
         sliderShape: 'circle',
         sliderType: 'temperature' // could also be 'hue', 'saturation', 'value', etc...
      }
    }
]
```

**Comment by 13546777510** [comment]
@jaames It feels very cool, I am looking forward to this

**Comment by 13546777510** [comment]
@jaames I will use the strip slider more, but the prototype slider looks cooler.

**Comment by DanielPeinhopf** [comment]
Wow, great. 👍 Thanks @jaames.

**Comment by AtmiyaVaghela** [comment]
> <img alt="Screenshot 2019-10-21 at 01 08 32" width="327" src="https://user-images.githubusercontent.com/9112876/67168776-54d36300-f39f-11e9-8b66-6658ca102c0f.png">
> 
> I also tentatively implemented a circular slider type like the one used in @KaanMol's screenshot, but does anyone care about this in particular? Or is having a simple kelvin slider fine?

Excellent work! I want to use this in my project. Waiting for release iro.js 5.0

**Comment by jaames** [comment]
iro.js 5.0.0 is now in beta if anybody would like to test it! Obviously I don't recommend using it in production, and documentation is still in progress. 

From NPM:

```
$ npm install @jaames/iro@beta
```

Manual download:

https://raw.githubusercontent.com/jaames/iro.js/v5-dev/dist/iro.min.js

To add a temperature slider you need to use the `layout` option to specify a custom layout:

```js
var colorPicker = new iro.ColorPicker('#color-picker', {
  layout: [
    {
      component: iro.ui.Wheel,
      options: {}
    },
    // Regular slider:
    {
      component: iro.ui.Slider,
      options: {}
    },
    // Temperature slider:
    {
      component: iro.ui.Slider,
      options: {
        sliderType: 'kelvin',
        // Optional: uncomment the next line if you want a circular slider like in the original request
        // sliderShape: 'circle'
      }
    }
  ]
});
```

**Comment by jaames** [comment]
@DanielPeinhopf oh sorry, add `layoutDirection: 'horizontal'` to the slider :)

**Comment by jaames** [comment]
@AtmiyaVaghela you can re-render the color picker with a new layout with the `updateOptions` method

```js
var colorPicker = new iro.ColorPicker('#color-picker', {
  layout: [
    ... initial layout
  ]
});

// update color picker layout whenever you like
colorPicker.updateOptions({
  layout: [
    ... new layout
  ]
})
```

**Comment by DanielPeinhopf** [comment]
> 
> 
> @DanielPeinhopf oh sorry, add `layoutDirection: 'horizontal'` to the slider :)

Thank you. I thought it would be vertical because of the vertical slider orientation inside of the wheel.
But it works :)

**Comment by AtmiyaVaghela** [comment]
> @AtmiyaVaghela you can re-render the color picker with a new layout with the `updateOptions` method
> 
> ```js
> var colorPicker = new iro.ColorPicker('#color-picker', {
>   layout: [
>     ... initial layout
>   ]
> });
> 
> // update color picker layout whenever you like
> colorPicker.updateOptions({
>   layout: [
>     ... new layout
>   ]
> })
> ```



> @AtmiyaVaghela you can re-render the color picker with a new layout with the `updateOptions` method
> 
> ```js
> var colorPicker = new iro.ColorPicker('#color-picker', {
>   layout: [
>     ... initial layout
>   ]
> });
> 
> // update color picker layout whenever you like
> colorPicker.updateOptions({
>   layout: [
>     ... new layout
>   ]
> })
> ```

Thank you very much. You have done a great job.

**Comment by jaames** [comment]
Sorry for such a slow response on this, things have been super busy for me recently. ':)

iro.js v5 is finally done, which includes a new kelvin slider type (as well as circular sliders!). If you update to the latest version, you can create a circular kelvin slider like so:

```js
var colorPicker = new iro.ColorPicker('#picker', {
  layout: {
    { 
      component: iro.ui.Slider,
      options: {
        sliderType: 'kelvin' ,
        sliderShape: 'circle'
      }
    },
  }
});
```

Relevant documentation: https://iro.js.org/advanced.html#sliders
