### ISSUE TITLE
watch for final color after user stops touching the wheel

### ISSUE THREAD

**Issue by mspanish** [jaames/iro.js#7]
Hello, lovely library! It would be great if the watch functionality also had the ability to detect if the user is done manipulating the color, in the case that you are running a function afterwards. For example, I add colors to a palettes once the user has chosen a color. Right now, using the watch function, it adds a ton of colors if the user swipes their finger around the wheel - as it adds 1 each time it detects a change. I'd rather only add a color once they are done - as right now it will add 20 or 30 in just a couple of seconds.

I am going to try adding a listener inside the watch fn and see if I can capture the touch end or something.

thanks again!

**Comment by jaames** [comment]
Hello, thank you for the suggestion!

I think I'll try to implement a proper event system that lets you add callbacks for different events, perhaps something like this?

```js
// add a callback function for when the user finishes selecting a color
colorWheel.on("selectionEnd", function(){ });

// add a callback function for when the user starts selecting a color
colorWheel.on("selectionStart", function(){ });

// the same as `watch`
colorWheel.on("colorChange", function(){ });
```

How does that sound? (:

**Comment by mspanish** [comment]
sounds great thanks for the speedy reply!

**Comment by jaames** [comment]
No worries! Just pushed that feature now, and updated some of the docs too: https://github.com/jaames/iro.js/blob/master/docs/colorPicker_api.md#on

I hope that suits your needs c:

**Comment by mspanish** [comment]
thank you!
