### ISSUE TITLE
Feature request: a way to distinguish between multiple pickers

### ISSUE THREAD

**Issue by BabyDead** [jaames/iro.js#71]
As-is, there seems to be no way to distinguish between which picker has been used when you have multiple instances.

The 'this' within the eventlistener 'color:change' seems to just return the window, so likely isn't set. There's also no event which gets passed to the function parameters, so I can't find a target or anything either.

It would be pretty great if I could find out which picker is being called upon, whether through an instance name, finding it through the element (by going through the DOM or adding a custom class or something) or through an event.

**Comment by jaames** [comment]
Hey!

It should be possible to pass the current color picker instance to the event's `this` context. By itself it wouldn't be that useful, though. Maybe an additional `id` option for the color picker could work?

**Comment by jaames** [comment]
I just pushed this feature in iro.js ver 4.5.0!

You can add a unique ID to the color picker:

```js
var colorPicker = new iro.ColorPicker({
  id: 'picker1',
  ...
})
```

The event callback's `this` context also gets bound to the active color picker now:

``` js
colorPicker.on("color:update", function() {
  // this === colorPicker
  if (this.id === 'picker1') {
    // do something ...
  }
})
```

Hope that helps to you accomplish what you need do! If you need anything else, feel free to add a new comment or open a new issue thread :)
