### ISSUE TITLE
moun and unmout color picker

### ISSUE THREAD

**Issue by artmelkon** [jaames/iro.js#73]
Can you please show how to mount or unmount the color picker.
Thanks in advanced.

**Comment by jaames** [comment]
Create a color picker:

```js
var colorPicker = new iro.ColorPicker({
  ...
})
```

Unmount from current DOM:

```js
colorPicker.el.removeChild(colorPicker.base);
colorPicker.el = null;
```

Mount to new DOM:

```js
newElement.addChild(colorPicker.base);
colorPicler.el = newElement;
```

**Comment by artmelkon** [comment]
Does the code works with API?
It keep throwing an error "colorPicker.el is undefined"
Thanks

**Comment by jaames** [comment]
Are you using the latest version of iro.js? (`iro.version` should be `"4.5.0"` or so)

Otherwise you may need to change `colorPicker` to whichever var your color picker is assigned to

**Comment by artmelkon** [comment]
I use this CDN link: https://cdn.jsdelivr.net/npm/@jaames/iro/dist/iro.min.js

**Comment by jaames** [comment]
Looks like you're using the latest version then.

I'm not sure why you're getting that error, without seeing your code I can only make guesses.

**Comment by artmelkon** [comment]
html
---------
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>repl.it</title>
    <link href="style.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/@jaames/iro/dist/iro.min.js"></script>
  </head>
  <body>
    <div id="test-picker"></div>
    <script src="script.js"></script>
  </body>
</html>
--------------
script.js
-----------
var colorPicker = new iro.ColorPicker('div', { width: 200 });

colorPicker.el.removeChild(colorPicker.base);
colorPicker.el = null

**Comment by jaames** [comment]
You need a HTML element for the color picker to mount to first:

```html
<html>
  <head>
    <title>repl.it</title>
    <script src="https://cdn.jsdelivr.net/npm/@jaames/iro/dist/iro.min.js"></script>
  </head>
  <body>
    <!-- color picker element -->
    <div class="colorPicker"></div>
    <script>
      var colorPicker = new iro.ColorPicker('.colorPicker', { width: 200 });
      // ... and so on
    </script>
  </body>
</html>
```

I'd recommend looking at the codepen demo https://codepen.io/rakujira/pen/WZOeNq?editors=1010 :)

**Comment by artmelkon** [comment]
I tried both ways, but still same error. I will keep testing. And the link you sent, it refers to the original color picker page you have on codepen, right?

**Comment by artmelkon** [comment]
Here, I have recreated the error: https://codepen.io/artmelkon/pen/wbVMZz?editors=1010
Thank you anyway for the help. I have a project where I am going to use your color picker. So I will be back with more questions :)

**Comment by jaames** [comment]
Ohh, I think you need to wait for the colorPicker's `mount` event:

```js
var colorPicker = new iro.ColorPicker('#color-picker', { width: 200 });

colorPicker.on('mount', function() {
  colorPicker.el.removeChild(colorPicker.base);
  colorPicker.el = null;
  console.log(colorPicker.el)
})
```

When the color picker is created, the HTML DOM isn't necessarily ready yet :)

Documentation: https://iro.js.org/colorPicker_api.html#events

**Comment by artmelkon** [comment]
Ahh, it did work , thank you.

**Comment by jaames** [comment]
No worries!

**Comment by artmelkon** [comment]
can you please tell what children: Array[] is for?

**Comment by jaames** [comment]
In what context? That doesn't sound like something from iro.js

**Comment by artmelkon** [comment]
Sorry, couldn't find it anymore. I was running a script and it appeared in the console, but now I don't see it.
