### ISSUE TITLE
how to set initial color dynamically

### ISSUE THREAD

**Issue by artmelkon** [jaames/iro.js#74]
Hello James,
I would like to set the initial color dynamically, I've been trying but wasn't able to solve it.
When I place call within the listener, it doesn't do anything.
color.set('#ff0');
https://codepen.io/artmelkon/pen/Ybmrbp?editors=1010

Is there way to do it?
Thanks in advanced.

**Comment by jaames** [comment]
Hey!

To set the initial color of the picker: 

```
var colorPicker = new iro.ColorPicker('.color-picker', {
  color: "#ff0"
})
```

If you need to modify the color after it changes, you need to set either `color.rgb`, `color.hsv` or `color.hsl` (I think `color.set` not working is actually a bug?)

```js
colorPicker.on('color:change', function(color) {
  color.rgb = { r: 255, g: 255, b: 0 };
})
```

**Comment by jaames** [comment]
Update: I looked into it, there isn't any bug with `color.set()`. You just need to remove `colorPicker.forceUpdate()`

**Comment by artmelkon** [comment]
I did remove colorPicker.forceUpdate()

When I type 'colorPicer.color.set('#ff0') in the console, it does sets the hex color as I enter, but when I place it in the script it won't do anything.

**Comment by artmelkon** [comment]
I notice when I have 'color:init', it works but  the color wheel disappears leaving only the slider.
And there is an error message: TypeError: n.onMount is not a function
https://codepen.io/artmelkon/pen/Ybmrbp?editors=1010
Is there way to get color wheel visible?
Thanks

**Comment by jaames** [comment]
Yeah I only just noticed that myself -- that *is* actually a bug. The reason it happens is because technically the color picker can't render until the page contents is loaded, so updating the color (which causes a rerender) before the page is ready was breaking things

I pushed a fix, so please make sure you're using iro.js `4.5.1`. It may take a little while before the CDN updates :)

**Comment by artmelkon** [comment]
Awesome, thank so much

**Comment by jaames** [comment]
No problem!

**Comment by artmelkon** [comment]
You fixed it, that's awesome, works like charm.
Thank you James!
