### ISSUE TITLE
I have element focus issue

### ISSUE THREAD

**Issue by artmelkon** [jaames/iro.js#75]
I am trying to change color on each individual box, even though I set them blur and one of them active, still the colors are being manipulated on all three of them.
Can you please check if this is on my end, or is there something could be done to change each box separately.

https://repl.it/@artmelkon/color-picker-v2

Thanks.

**Comment by jaames** [comment]
I'm struggling to make sense of some of the code here; but maybe need to remove the previous `color:change` event listener when you change focus to a new box? You can do this with the color picker's `off` method: https://iro.js.org/colorPicker_api.html#off

To be honest, while I'm happy to fix bugs in iro.js and answer general questions about how to achieve certain things with the library, I can't really offer support for bugs in whatever application you're building around iro.js. Maintaining an open-source project already requires a lot of time and work, and unfortunately I don't really have much time to spare for debugging other people's projects. 

Sorry.

**Comment by artmelkon** [comment]
Hey James,
Thank you for your help and I totally understand.
The color picker is to change the colors on a pattern dynamically.
Thanks again.
Arthur

**Comment by artmelkon** [comment]
Hey James,
I got it working, thank you for the hint.

**Comment by jaames** [comment]
Cool, glad that helped!
