### ISSUE TITLE
Opacity slider

### ISSUE THREAD

**Issue by artmelkon** [jaames/iro.js#79]
I tried the sliderType initiate as opacity/transparency but none of them worked.
My brightness slider and opacity linked together, when you move one, the other moves with it.
How could I do that?
Here is the link https://repl.it/@artmelkon/HSL-color-picker-individual-v1-1

Thanks,
Arthur

**Comment by jaames** [comment]
Hey Arthur,

Transparency is supported via a plugin; https://github.com/jaames/iro-transparency-plugin

**Comment by artmelkon** [comment]
Got the CDN,
Thank you so much
