### ISSUE TITLE
pointer is not moving when we setState in onColorChange in React

### ISSUE THREAD

**Issue by spicynaresh** [jaames/iro.js#82]
pointer visually is not moving but functionality is working
issue is in below link 
https://codesandbox.io/s/github/spicynaresh/React-Color-Picker-IRO

onColorChange = color => {
    this.setState({
      color:color
    })
    console.log(color.hexString);
  };
  render() {
    console.log(this.state.color);
    return (
      <div className="App">
        <IroColorPicker color={"#fff"} onColorChange={this.onColorChange} />
      </div>
    );
  }
}

**Comment by spicynaresh** [comment]
@jaames any suggestions

**Comment by jaames** [comment]
@spicynaresh You probably want to set IroColorPicker's `color` prop to `this.state.color`

```jsx
<IroColorPicker color={ this.state.color } onColorChange={this.onColorChange} />
```

**Comment by spicynaresh** [comment]
thanks for quick response

**Comment by jaames** [comment]
No worries :)
