### ISSUE TITLE
missing wheel component margin

### ISSUE THREAD

**Issue by FryerTuck** [jaames/iro.js#86]
### To the point
First of all: amazing library, thanks!
While this may be a feature request, this is causing some UI issues for me as I can adjust the slider margins, but, what if I need more space between the wheel and sliders, and less space between the sliders?

Have a look at this screenshot for clarity:
[![Screenshot-20191013-130431.png](https://i.postimg.cc/9fk0vsvY/Screenshot-20191013-130431.png)](https://postimg.cc/Y41tFD2v)

The degree-marks around the wheel is NOT just eye-candy; it's a UI component to choose the ***angle*** and direction to which ***linear gradient*** is rendered, but this is not in the scope of this color-picker component; was just saying that I really do need extra space there, but if I implement a larger `sliderMargin` then the UI becomes too "tall" - I need less space between the sliders and more space directly below the wheel.

Is there a way I can achieve this without too much hacking?
I've tried the `layouts` definition with some related options, but, maybe I'm just missing something.

### margin-spec and standardization
Would it be okay if a `wheelMargin` property is requested?
This property spec could be really simple like:
- either `wheelMargin: 10,`
- or `wheeMargin: [5,10,0,20]`

The same could be assumed for the `sliderMargin`?

**Comment by jaames** [comment]
You can use the `layouts` option to get a bit more flexibility, including passing different `sliderMargin` values to each slider: 

```js
iro.use(iroTransparencyPlugin);

// create a new color picker instance
// https://iro.js.org/guide.html#getting-started
var colorPicker = new iro.ColorPicker(".colorPicker", {
  // color picker options
  //https://iro.js.org/guide.html#color-picker-options
  width: 280,
  color: "rgb(255, 0, 0)",
  borderWidth: 1,
  borderColor: "#fff",
  // custom layout   
  // https://iro.js.org/guide.html#custom-layouts
  layout: [
    {
      component: iro.ui.Wheel,
      options: {}
    },
    {
      component: iro.ui.Slider,
      options: { sliderMargin: 12 }
    },
    {
      component: iro.ui.TransparencySlider,
      options: { sliderMargin: 8 } // different sliderMargin for the transparency slider
    }
  ]
});
```

I'll see if there's anything I can do to make this easier and to improve the documentation on this subject, since I realise it's not exactly obvious. I'll add it to the iro.js 5.0 thread (#83).

Thanks! :)

**Comment by FryerTuck** [comment]
Awesome!<br>
**pitfall**
- if you use this, you need to ***remove this attribute***: `transparency:true,`

else you get 2 transparency sliders :D
