### ISSUE TITLE
Impossible to get #ffffff

### ISSUE THREAD

**Issue by redpik** [jaames/iro.js#90]
It's impossible.

**Comment by jaames** [comment]
Can you please explain the issue in more detail? "its impossible" isnt much to go on

**Comment by redpik** [comment]
https://codepen.io/rakujira/full/WZOeNq

Try to obtain #000000 : easy.
Try to obtain #FF0000 : possible.
Try to obtain #FFFFFF : impossible.

**Comment by jaames** [comment]
I see, you're talking about trying to get specific colors?

To be honest that's... kinda the point of this style of color picker. It's for cases where the precision of a color isn't super important, like RGB lighting.

That said, you can use the [Custom Layout](https://iro.js.org/guide.html#custom-layouts) feature to add a saturation slider if you want, which will make it easier:

```js
var colorPicker = new iro.ColorPicker('#color-picker', {
  layout: [
    {
      // wheel
      component: iro.ui.Wheel,
      options: {
      }
    },
    {
      // value slider
      component: iro.ui.Slider,
      options: {
      }
    },
    {
      // saturation slider
      component: iro.ui.Slider,
      options: {
        sliderType: 'saturation'
      }
    },
  ]
});
```

Or you can wait for [iro.js 5.0](https://github.com/jaames/iro.js/issues/83), which will have more precise color picker controls available

**Comment by redpik** [comment]
Okay, thank you for your answers.
