### ISSUE TITLE
Setting the Color Picker color "externally" via JS

### ISSUE THREAD

**Issue by danielschlingmeier** [jaames/iro.js#93]
Hello! Its me again! :)

I have one more question about the colorpicker (hopefully the last one :-)):

I have the need to update the colorpicker externally via JavaScript, which is because the selected color may be changed by another application and therefore I read it back from server and try to update the colorpicker via JavaScript. According to your documentation this shall be possible, but I can't get it running :(

So I create an object with some options and define an event handler:

>var colorPicker = new iro.ColorPicker("#color-picker-container", {
  width: 250,           // Set the size of the color picker
  color: "#f00",        // Set the initial color to pure red
  borderWidth: 2, 
  borderColor: "#ccc"
});
colorPicker.on('color:change', setColor);

I can access the actual color via:

> var rgbcolor = colorPicker.color.rgb;
r = rbgcolor.r;
....

This all works fine so far! Now I try to write the color "externally":

> colorPicker.color.rgb.r = answer.r;
colorPicker.color.rgb.g = answer.g;
colorPicker.color.rgb.b = answer.b;

However this doesn't affect the position of the selector. I tried the .reset() methods, but this sets the color back to the one from the option handed over to the constructor, but not this one here. (answer is just an object here generated via JSON.parse(), it contains the r, g, b values.

So how does this: 

> An iro.Color object representing the currently selected color. Updating this color object will also update the seclected color in the picker.

work? :-)

Thanks in advance!

Best regards 
Daniel

**Comment by jaames** [comment]
Hi!

iro.js only listens for changes on direct color properties like `color.rgb` or `color.hsl`, and not sub-properties such as `rgb.r` or `hsl.s`. You'll need to set all the values of `colorPicker.color.rgb` in one go, like:

```js
colorPicker.color.rgb = { r: answer.r, g: answer.g, b: answer.b }
```

For reference, when you set one of the color properties in iro.js, it fires a bunch of events internally which results in the wheel re-rendering. If you were to set all of those sub-properties individually, this would actually fire all those events and re-render the wheel three times: 

```js
colorPicker.color.rgb.r = answer.r;
// color picker sees that rgb.r changed, re-renders
colorPicker.color.rgb.g = answer.g;
// color picker sees that rgb.g changed, re-renders
colorPicker.color.rgb.b = answer.b;
// color picker sees that rgb.b changed, re-renders
````

Which probably isn't what you intended, hence I figured sub-properties should be ignored. It keeps the code much cleaner too. :P

**Comment by danielschlingmeier** [comment]
Hello! Yes well, firing 3x is not what I intend, no, but actually it doesn't seem to fire any event if the sub-properties r, g, b are changed. However it works fine if I change the color with the access method you proposed. Very nice! Thanks very much once again! :-)
