### ISSUE TITLE
transparency slider rendered twice with two ColorPicker instances 

### ISSUE THREAD

**Issue by inconduit** [jaames/iro.js#95]
i'm using ColorPicker in a react project and instantiating it per the advice in another issue. i'm opting to not show the brightness slider by providing the layout prop array as per the docs.

if i render only one instance of this component, everything is fine. when i render a second one, the transparency slider gets rendered twice in both components.  am i missing something in the docs? is this a bug? 

i noticed that if i do include the brightness slider (by not including a `layout` prop) the transparency slider does not double render, maybe that's a hint?

![image](https://user-images.githubusercontent.com/1611256/72172436-244e0480-33a3-11ea-8076-1017fa6edf9b.png)

```
import iro from '@jaames/iro';
import iroTransparencyPlugin from 'iro-transparency-plugin';
iro.use(iroTransparencyPlugin);

  componentDidMount() {
  this.colorPicker =
    new iro.ColorPicker(
      this.node, 
      {
        transparency: true,
        layout: [{ component: iro.ui.Wheel,  options: {}}]
      }
    )
  }

   render() {
     <div ref={node => this.node = node} />
   }
```

**Comment by jaames** [comment]
Sorry for the slow response on this. This should no longer be an issue as the transparency plugin has been deprecated, and the transparency slider is now part of the core library: https://iro.js.org/advanced.html#sliders
