### ISSUE TITLE
Converting and setting brightness

### ISSUE THREAD

**Issue by atchoo78** [jaames/iro.js#99]
Hello,

Thank you for creating this. When working with certain RGB/HSV compatible lights that expect a dim/brightness value (Lifx, Hue, Neopixels etc.), the following seems to work for me:

```javascript
var brightness = Math.round(color.hsv.v/100*255)

```

In the example above, "255" is the brightest value of the brightness range you are converting to.
If the range was 0-100 (e.g. for a percent based range), you would use "100" instead of "255".

Also, to get the individual RGB values:

```javascript
var red = color.rgb.r;
var green = color.rgb.g;
var blue = color.rgb.b;

```

Just wanted to share this, in case someone find it useful. 🎨

Best regards,

Andreas

**Comment by jaames** [comment]
Thanks for the notes! As of version 5.0, you can also get individual RGB values like this:

```js
var red = color.red;
var green = color.green;
var blue = color.blue;
```
